// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migration/introspection commands need a direct PostgreSQL connection.
    // Runtime Prisma continues to use DATABASE_URL (the Supabase pooler) in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
